//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Youtube.Playlist.Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Youtube.Playlist.Downloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;MS Youtube Downloader Tracking page&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;form action=&apos;https://www.paypal.com/cgi-bin/webscr&apos; method=&apos;post&apos; target=&apos;_blank&apos;&gt;
        ///&lt;input type=&apos;hidden&apos; name=&apos;cmd&apos; value=&apos;_s-xclick&apos;&gt;
        ///&lt;input type=&apos;hidden&apos; name=&apos;hosted_button_id&apos; value=&apos;C79LKUFBTF66N&apos;&gt;
        ///&lt;input type=&apos;image&apos; src=&apos;https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif&apos; border=&apos;0&apos; name=&apos;submit&apos; alt=&apos;PayPal - The safer, easier way to pay online!&apos;&gt;
        ///&lt;img alt=&apos;&apos; border=&apos;0&apos; src=&apos;https://www.paypalobjects.com/en_US/i/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TrackerHtml {
            get {
                return ResourceManager.GetString("TrackerHtml", resourceCulture);
            }
        }
    }
}
